{{- /*
Copyright Â© 2024 Open Notebook Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/ -}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.names.fullname" . }}
  namespace: {{ include "common.names.namespace" . }}
  labels: {{- include "open-notebook.labels" . | nindent 4 }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.service.annotations "context" $ ) | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  sessionAffinity: {{ .Values.service.sessionAffinity }}
  {{- if .Values.service.sessionAffinityConfig }}
  sessionAffinityConfig: {{- include "common.tplvalues.render" (dict "value" .Values.service.sessionAffinityConfig "context" $) | nindent 4 }}
  {{- end }}
  ports:
    - name: http
      port: {{ .Values.service.ports.http }}
      targetPort: http
      protocol: TCP
      {{- if and (eq .Values.service.type "NodePort") .Values.service.ports.httpNodePort }}
      nodePort: {{ .Values.service.ports.httpNodePort }}
      {{- end }}
    - name: api
      port: {{ .Values.service.ports.api }}
      targetPort: api
      protocol: TCP
      {{- if and (eq .Values.service.type "NodePort") .Values.service.ports.apiNodePort }}
      nodePort: {{ .Values.service.ports.apiNodePort }}
      {{- end }}
  selector: {{- include "open-notebook.selectorLabels" . | nindent 4 }}

---
{{- if .Values.surrealdb.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.names.fullname" . }}-surrealdb
  namespace: {{ include "common.names.namespace" . }}
  labels: {{- include "open-notebook.surrealdb.labels" . | nindent 4 }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.surrealdb.service.annotations "context" $ ) | nindent 4 }}
spec:
  type: {{ .Values.surrealdb.service.type }}
  ports:
    - name: http
      port: {{ .Values.surrealdb.service.port }}
      targetPort: http
      protocol: TCP
      {{- if and (eq .Values.surrealdb.service.type "NodePort") .Values.surrealdb.service.nodePort }}
      nodePort: {{ .Values.surrealdb.service.nodePort }}
      {{- end }}
  selector: {{- include "open-notebook.surrealdb.selectorLabels" . | nindent 4 }}
{{- end }}
